<?php

/**
 * Created by PhpStorm.
 * User: axlrose
 * Date: 16/7/11
 * Time: 上午10:47
 */
namespace echotrue\foobar;

class Assets extends \yii\web\AssetBundle
{
    public $css     = [
        'css/style.css',
        'css/editormd.css'
    ];
    public $js      = [
        'js/editormd.min.js'
    ];
    public $depends = [

    ];

    public function init()
    {
        $this->sourcePath = __DIR__ . '/';
        parent::init(); // TODO: Change the autogenerated stub

    }
}