<?php

namespace echotrue\foobar;

use yii\helpers\Html;

/**
 * This is just an example.
 */
class AutoloadExample extends \yii\widgets\InputWidget
{

    public $attributes;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $view                   = $this->getView();
        $this->attributes['id'] = $this->options['id'];
        if ($this->hasModel()) {
            $input = Html::activeTextarea($this->model, $this->attribute, $this->attributes);
        } else {
            $input = Html::textarea($this->name, '', $this->attributes);
        }
        echo $input;
        Assets::register($view);

        $js = 'testEditor = editormd("' . $this->options['id'] . '", {
                    width   : "90 % ",
                    height  : 640,
                    syncScrolling : "single",
                    path    : " ../lib / "
                });';
        $view->registerJs($js, $view::POS_END);
    }

}
